import test from 'node:test';
import assert from 'node:assert/strict';
import { decisionMetric, projectPlayer } from '../lib/genie/projections';
import { buildDevelopmentDossier, isDevelopmentQuestion } from '../lib/genie/development';
import { buildPredictiveFrontOfficeReport, isPredictiveFrontOfficeQuestion, GENIE_PREDICTIVE_FRONT_OFFICE_VERSION } from '../lib/genie/predictiveFrontOffice';
import { auditGeniePayload, finalizeGeniePayload, GENIE_INTERNAL_AUDIT_VERSION } from '../lib/genie/reliability';
import { analyzeOrganization } from '../lib/genie/organization';
import { simulateScenario } from '../lib/genie/simulation';
import { buildFrontOfficeReport } from '../lib/genie/frontoffice';
import { selectGenieRoute } from '../lib/genie/router';
import { buildGenieContext } from '../lib/genie/context';
import { reconcileMatchedPlayers } from '../lib/genie/claude';
import { enrichRankings } from '../lib/ranking/intelligence';
import type { PlayerEvidence } from '../lib/genie/types';

const scores={overall:70,ceiling:75,floor:60,performance:72,momentum:74,readiness:68,power:65,speed:40,contact:62,discipline:58,strikeouts:0,command:0,risk:42};
const evidence:PlayerEvidence={player:{player:'Test Prospect',age:21,level:'AA'},stat:{player:'Test Prospect',currentAge:21,level:'AA'},promotions:[],scores,strengths:['performance'],concerns:[]};

test('promotion and trade questions route to the correct decision metric',()=>{assert.equal(decisionMetric('Should Test Prospect be promoted?'),'promotionProbability');assert.equal(decisionMetric('What is his trade value?'),'tradeValue');});

test('specialized route priority matches user intent',()=>{assert.equal(selectGenieRoute('Who has improved the most recently, and why?',0),'core');assert.equal(selectGenieRoute('Is Aidan Miller actually getting better?',1),'development_dossier');assert.equal(selectGenieRoute('Should Aidan Miller be promoted?',1),'front_office_decision');assert.equal(selectGenieRoute('What if the Phillies promote Aidan Miller to MLB?',1),'simulation');assert.equal(selectGenieRoute('Project the Phillies organization in 2028',0),'predictive_front_office');assert.equal(selectGenieRoute('What are the farm system strengths?',0),'organization');});

test('Genie context snapshot includes canonical rankings and every tracked player name',()=>{const canonical=enrichRankings();const context=buildGenieContext();assert.ok(context.text.includes('PHILLIES PROSPECT RANKINGS'));assert.equal(context.playerNames.length,canonical.length);for(const player of canonical)assert.ok(context.text.includes(player.player));});
test('reconcileMatchedPlayers separates tracked names from unrecognized ones',()=>{const tracked=enrichRankings().slice(0,3).map(row=>row.player);const{recognized,unrecognized}=reconcileMatchedPlayers([tracked[0],'Not A Real Prospect'],tracked);assert.deepEqual(recognized,[tracked[0]]);assert.deepEqual(unrecognized,['Not A Real Prospect']);});

test('projection scores remain bounded and include explanations',()=>{const result=projectPlayer(evidence);for(const value of [result.mlbProbability,result.promotionProbability,result.breakoutProbability,result.tradeValue,result.protectScore,result.volatility])assert.ok(value>=0&&value<=100);assert.ok(result.drivers.length>=4);assert.ok(result.drivers.every(driver=>driver.explanation.length>0));});
test('injuries lower near-term projection outcomes',()=>{const healthy=projectPlayer(evidence);const injured=projectPlayer({...evidence,injury:{player:'Test Prospect',status:'Injured'}});assert.ok(injured.mlbProbability<healthy.mlbProbability);assert.ok(injured.promotionProbability<healthy.promotionProbability);});

test('development questions route to Genie 9.0',()=>{assert.equal(isDevelopmentQuestion('Is Aidan Miller actually getting better?'),true);assert.equal(isDevelopmentQuestion('Show me his living scouting dossier'),true);assert.equal(isDevelopmentQuestion('What is his trade value?'),false);});
test('development dossier degrades safely without Supabase history',async()=>{const dossier=await buildDevelopmentDossier('Aidan Miller');assert.equal(dossier.player,'Aidan Miller');assert.ok(dossier.developmentScore>=0&&dossier.developmentScore<=100);assert.ok(dossier.developmentConfidence>=0&&dossier.developmentConfidence<=100);assert.ok(dossier.answer.includes('development dossier'));assert.ok(dossier.limitations.length>0);});

test('predictive front office questions route to Genie 10.0',()=>{assert.equal(isPredictiveFrontOfficeQuestion('Project the Phillies 26-man roster for the next three seasons'),true);assert.equal(isPredictiveFrontOfficeQuestion('Who needs 40-man protection from the Rule 5 draft?'),true);assert.equal(isPredictiveFrontOfficeQuestion('Simulate a trade package built around Aidan Miller'),true);assert.equal(isPredictiveFrontOfficeQuestion('Is Aidan Miller getting better?'),false);assert.equal(GENIE_PREDICTIVE_FRONT_OFFICE_VERSION,'10.0.1');});
test('Genie 10 produces three bounded future roster scenarios and protection decisions',async()=>{const report=await buildPredictiveFrontOfficeReport('Project the Phillies 26-man roster and Rule 5 decisions for the next three seasons',[]);assert.equal(report.version,'10.0.1');assert.equal(report.futureRosters.length,3);assert.ok(report.futureRosters.every(roster=>roster.players.length<=26));assert.ok(report.futureRosters.every(roster=>roster.season>new Date().getUTCFullYear()));assert.ok(report.futureRosters.every(roster=>roster.positionPressure.every(item=>item.pressure>=0&&item.pressure<=100)));assert.ok(report.fortyMan.projectedPressure>=0&&report.fortyMan.projectedPressure<=100);assert.ok(report.fortyMan.decisions.length>0);assert.ok(report.rule5.decisions.every(item=>item.protectionScore>=0&&item.protectionScore<=100));assert.ok(report.answer.includes('Predictive Front Office v10.0'));assert.ok(report.answer.includes('Current roster source:'));});
test('Genie 10 builds a minimal multi-player impact package around the named anchor',async()=>{const report=await buildPredictiveFrontOfficeReport('Simulate an impact trade package around Aidan Miller',['Aidan Miller']);assert.ok(report.tradePackage);assert.ok((report.tradePackage?.packageValue??-1)>=0&&(report.tradePackage?.packageValue??101)<=100);assert.equal(report.tradePackage?.targetTier,'impact');assert.ok(report.tradePackage?.players.includes('Aidan Miller'));assert.ok((report.tradePackage?.players.length??0)>=1);assert.ok((report.tradePackage?.players.length??0)<=4);});

test('organization leaders are selected from canonical v4 ranks',()=>{const canonical=enrichRankings();const report=analyzeOrganization('What are the Phillies farm system strengths?');for(const group of report.groups){for(const leader of group.leaders){const leaderRank=canonical.find(row=>row.player===leader)?.rank??999;const sameGroupRanks=canonical.filter(row=>{const p=String(row.position||'').toUpperCase();const groupName=['RHP','LHP','P','SP','RP'].includes(p)?'Pitching':p==='C'?'Catcher':['SS','2B','3B','1B','IF'].includes(p)?'Infield':['CF','LF','RF','OF'].includes(p)?'Outfield':'Other';return groupName===group.group;}).map(row=>row.rank).sort((a,b)=>a-b).slice(0,3);assert.ok(sameGroupRanks.includes(leaderRank));}}});
test('farm-system simulation baseline uses canonical v4 scores',()=>{const canonical=enrichRankings();const report=simulateScenario('What if the Phillies draft 1 pitcher?');const pitching=report.baseline.groups.find(group=>group.group==='Pitching');const pitcherScores=canonical.filter(row=>/^(P|RHP|LHP|SP|RP)$/i.test(String(row.position||''))).map(row=>row.score);const expected=pitcherScores.reduce((sum,value)=>sum+value,0)/pitcherScores.length;assert.ok(pitching);assert.ok(Math.abs((pitching?.averageScore??0)-expected)<.11);});
test('promotion board exposes canonical rank and score for every player',()=>{const canonical=enrichRankings();const report=buildFrontOfficeReport('Show me the promotion board',[]);assert.ok(report.promotionBoard.length>0);for(const player of report.promotionBoard){const ranking=canonical.find(row=>row.player===player.player);assert.equal(player.rank,ranking?.rank);assert.equal(player.score,ranking?.score);}});

test('internal reliability guardrail is not presented as Genie layer 10',()=>{const top=enrichRankings()[0];const payload={answer:`${top.player} is the current top-ranked prospect.`,matchedPlayers:[top.player],intent:{task:'player_profile'},confidence:'high',limitations:[],evidence:[{player:top.player,currentScores:{overall:top.score}}]};const audit=auditGeniePayload(payload);assert.equal(audit.version,GENIE_INTERNAL_AUDIT_VERSION);assert.equal('layer' in audit,false);assert.equal(audit.passed,true);const finalized=finalizeGeniePayload({engine:'Prospect Genie Predictive Front Office v10.0',...payload});assert.equal(finalized.engine,'Prospect Genie Predictive Front Office v10.0');});
test('reliability guardrail catches canonical score disagreements',()=>{const top=enrichRankings()[0];const audit=auditGeniePayload({answer:'This answer is long enough to be audited correctly.',matchedPlayers:[top.player],intent:{task:'player_profile'},limitations:[],evidence:[{player:top.player,currentScores:{overall:top.score-10}}]});assert.equal(audit.passed,false);assert.ok(audit.checks.some(check=>check.id==='canonical-ranking-consistency'&&!check.passed));});
