create table if not exists public.player_snapshots (
  id bigint generated by default as identity primary key,
  player_id text not null,
  player_name text not null,
  captured_at timestamptz not null default now(),
  snapshot_date date generated always as ((captured_at at time zone 'utc')::date) stored,
  season integer,
  level text,
  affiliate text,
  organization_rank integer,
  ranking_score numeric,
  injury_status text,
  stats jsonb not null default '{}'::jsonb,
  model_scores jsonb not null default '{}'::jsonb,
  projections jsonb not null default '{}'::jsonb,
  source_ids text[] not null default '{}',
  source_evidence jsonb not null default '[]'::jsonb,
  source_quality numeric not null default 0,
  unique(player_id, snapshot_date)
);

create index if not exists player_snapshots_player_date_idx on public.player_snapshots(player_id, captured_at desc);
create index if not exists player_snapshots_name_date_idx on public.player_snapshots(lower(player_name), captured_at desc);

create table if not exists public.data_sources (
  source_id text primary key,
  name text not null,
  source_type text not null,
  authority_tier integer not null check (authority_tier between 1 and 5),
  base_url text,
  permitted_use text not null,
  active boolean not null default true,
  notes text,
  updated_at timestamptz not null default now()
);

insert into public.data_sources(source_id,name,source_type,authority_tier,base_url,permitted_use,notes)
values
 ('mlb_stats_api','MLB Stats API','official_stats',5,'https://statsapi.mlb.com','Official player, roster, statistics and transaction data','Primary quantitative source.'),
 ('phillies_official','Philadelphia Phillies','official_news',5,'https://www.mlb.com/phillies','Official transactions, assignments and club announcements','Primary team-news source.'),
 ('milb_official','Minor League Baseball','official_stats',5,'https://www.milb.com','Official affiliated minor-league statistics and roster information','Use official feeds or pages only.'),
 ('local_rankings_model','Prospect Pulse Rankings','derived_model',3,null,'Internally calculated ranking snapshots','Must retain component scores and upstream source evidence.')
on conflict (source_id) do update set name=excluded.name, authority_tier=excluded.authority_tier, permitted_use=excluded.permitted_use, notes=excluded.notes, updated_at=now();

alter table public.player_snapshots enable row level security;
alter table public.data_sources enable row level security;
